# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Hector Leon Zarco Garcia"
description: > # this means to ignore newlines until "email:"
   An a wonderful stack trace

email: hezarco@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Hector Leon Zarco Garcia'
author: 'Hector Leon Zarco Garcia'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/zzarcon
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/zzarcon
    desc:	Fork me on github
    share_url:
    share_title:
    share_link: